server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          #uri: https://github.com/krish/spring-cloud-config-store
          uri: https://github.com/hravada/ffff
          search-paths:
           - '*service'



